---
# tasks file for dns
- name: "packages"
  package:
    name: '{{ item }}'
  with_items:
    - '{{ dns_packages }}'
  notify: 'start bind'
  tags:
    - dns
    - packages

- name: "{{ dns_default_file }}"
  lineinfile:
    dest: '{{ dns_default_file }}'
    regexp: '^OPTIONS=.*$'
    line: 'OPTIONS="-u {{ dns_user }} -t {{ dns_chroot }}"'
  notify: 'start bind'
  tags:
    - dns
    - default

- name: "check if /etc/bind/README.{{ dns_domain }} exists"
  stat:
    path: '/etc/bind/README.{{ dns_domain }}'
  register: README
  tags:
    - dns
    - readme

- name: "{{ dns_chroot }} folders"
  file:
    path: '{{ item }}'
    state: directory
    owner: 'root'
    group: '{{ dns_user }}'
    mode: '2775'
  with_items:
    - '{{ dns_chroot }}/etc/bind'
    - '{{ dns_chroot }}/etc/bind/zones'
    - '{{ dns_chroot }}/dev'
    - '{{ dns_chroot }}/var/run'
    - '{{ dns_chroot }}/var/cache/bind'
#  when: README.stat.exists == False
  notify: 'start bind'
  tags:
    - dns
    - folders

- name: "create device nodes in {{ dns_chroot }}"
  shell: "mknod {{ item.localdev }} c 1 {{ item.localvalue }}"
  args:
    creates: "{{ item.localdev }}"
  with_items:
    - { localdev: '{{ dns_chroot }}/dev/random',  localvalue: '8' }
    - { localdev: '{{ dns_chroot }}/dev/urandom', localvalue: '9' }
  notify: 'start bind'
  tags:
    - dns
    - devices

- name: "create DNSSEC key files"
  shell: 'dnssec-keygen -K /etc/bind -a HMAC-MD5 -b 128 -n HOST {{ dns_keyname }}'
  # when: ( Kfiles | failed ) and ( README.stat.exists == False )
  when: README.stat.exists == False
  register: Kfilescreated
  notify: 'start bind'
  tags:
    - dns
    - keys

- name: "display Kfilescreated"
  debug:
    var: Kfilescreated
  when: Kfilescreated | succeeded
  tags:
    - dns
    - keys

- name: "check that K{{ dns_keyname }} file(s) exists"
  shell: 'ls /etc/bind/K*.key'
  register: Kfiles
  ignore_errors: true
  when: dns_role == "master"
  tags:
    - dns
    - keys

- name: "display Kfiles"
  debug:
    var: Kfiles
  when: Kfiles | succeeded
#  when:
#    - dns_role == "master"
#    - Kfiles | succeeded
  tags:
    - dns
    - keys

- name: "get Kfiles name"
  set_fact:
    Kfilename: "{{ Kfiles.stdout }}"
  when: Kfilescreated | succeeded
  tags:
    - dns
    - keys
    - facts

- name: "display Kfilename"
  debug:
    msg: "{{ Kfilename }}"
  when: Kfilescreated | succeeded
  tags:
    - dns
    - keys
    - debug

- name: "extract key from {{ Kfilename }}"
  shell: "cat {{ Kfilename }}|cut -d' ' -f 7"
  register: rndckey
  # when: ( Kfilescreated | succeeded ) and ( README.stat.exists == False )
  when: Kfilescreated | succeeded
  tags:
    - dns
    - keys

- name: "display rndckey"
  debug:
    var: rndckey.stdout
  # when: ( rndckey | succeeded ) and ( README.stat.exists == False )
  when: rndckey | succeeded
  tags:
    - dns
    - keys

- name: "set rndckeyvalue"
  set_fact:
    rndckeyvalue: "{{ rndckey.stdout }}"
  # when: ( rndckey | succeeded ) and ( README.stat.exists == False )
  when: rndckey | succeeded
  tags:
    - dns
    - keys

- name: "check if /etc/bind/rndc.key exists"
  stat:
    path: '/etc/bind/rndc.key'
  register: rndckeyexists
  tags:
    - dns
    - keys

- name: "update /etc/bind/rndc.key with new key"
  lineinfile:
    dest: '/etc/bind/rndc.key'
    regexp: '^.*secret.*$'
    line: '        secret "{{ rndckey.stdout }}";'
  when: rndckeyexists.stat.exists
  tags:
    - dns
    - rndckey

- name: "copy /etc/bind content to {{ dns_chroot }}/etc/bind"
  shell: 'cp /etc/bind/{{ item }} {{ dns_chroot }}/etc/bind/'
  register: chrooted
  with_items:
    - rndc.key
  when: README.stat.exists == False
  notify: 'start bind'
  tags:
    - dns
    - chroot

- name: "move /etc/bind content to {{ dns_chroot }}/etc/bind"
  shell: 'mv /etc/bind/{{ item }} {{ dns_chroot }}/etc/bind/'
  register: chrooted
  with_items:
    - bind.keys
    - db.0
    - db.127
    - db.255
    - db.empty
    - db.local
    - db.root
    - named.conf
    - named.conf.default-zones
    - named.conf.local
    - named.conf.options
    - zones.rfc1918
    - rndc.key
  when: README.stat.exists == False
  notify: 'start bind'
  tags:
    - dns
    - chroot

- name: "create /etc/bind/README.{{ dns_domain }}"
  template:
    src: 'README.chroot.j2'
    dest: '/etc/bind/README.{{ dns_domain }}'
  when: chrooted | succeeded
  notify: 'start bind'
  tags:
    - dns
    - readme

- name: "named.conf.local in chroot"
  template:
    src: 'named.conf.local.j2'
    dest: '{{ dns_chroot }}/etc/bind/named.conf.local'
  notify: 'start bind'
  tags:
    - dns
    - local

- name: "named.conf.options"
  template:
    src: 'named.conf.options.j2'
    dest: '{{ dns_chroot }}/etc/bind/named.conf.options'
  notify: 'start bind'
  tags:
    - dns
    - options

- name: "create minimal zones files"
  template:
    src: 'zone.{{ item.type }}.j2'
    dest: '{{ dns_chroot }}/etc/bind/zones/{{ item.file }}'
    group: '{{ dns_user }}'
    mode: '0664'
  with_items: '{{ dns_zones }}'
  notify: 'start bind'
  when: README.stat.exists == False
  tags:
    - dns
    - zones
...
